name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.client }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - client: mahuat
            firebase_app_id: 1:583927464597:android:8cb71740c9919f2cacd19c

          # - client: omcuat
          #   firebase_app_id: 1:583927464597:android:6757b2e9691332beacd19c

          - client: skruat
            firebase_app_id: 1:583927464597:android:e5ac64cf40672d89acd19c

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Client Environment
        run: |
         mkdir -p src/config

         if [ "${{ matrix.client }}" = "mahuat" ]; then
         BASE_URL="${{ secrets.MAHUAT_BASE_URL }}"
         CLIENT_NAME="Mahuat"
         elif [ "${{ matrix.client }}" = "omcuat" ]; then
         BASE_URL="${{ secrets.OMCUAT_BASE_URL }}"
         CLIENT_NAME="Omcuat"
         else
         BASE_URL="${{ secrets.SKRUAT_BASE_URL }}"
         CLIENT_NAME="Skruat"
         fi

         printf 'export const BASE_URL = "%s";\nexport const CLIENT_NAME = "%s";\n' \
         "$BASE_URL" "$CLIENT_NAME" > src/config/env.js


      - name: Verify Environment
        run: |
         echo "===== CLIENT ====="
         echo "${{ matrix.client }}"
         echo "===== env.js ====="


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Node Modules
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle



      - name: Create Firebase Credentials
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Set Google Credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-service-account.json" >> $GITHUB_ENV

      - name: Restore Keystore Properties
        run: |
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > android/keystore.properties

      - name: Restore Release Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/docwise-release.keystore          
      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Capitalize Flavor Name
        run: |
          CLIENT=$(echo "${{ matrix.client }}" | sed 's/.*/\u&/')
          echo "CLIENT=$CLIENT" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd android
          ./gradlew assemble${CLIENT}Release

      - name: Verify APK Output
        run: |
          ls -R android/app/build/outputs/apk

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute \
            android/app/build/outputs/apk/${{ matrix.client }}/release/*.apk \
            --app ${{ matrix.firebase_app_id }} \
            --groups qa-testing \
            --release-notes "Automated build from GitHub Actions"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.client }}-apk
          path: android/app/build/outputs/apk/${{ matrix.client }}/release/*.apk

  approval-test:
    name: QA Approval
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: QA Approved
        run: |
          echo "====================================="
          echo "QA APPROVED THE BUILD ✅"
          echo "Workflow resumed successfully."
          echo "====================================="


  deploy-play:
    name: Deploy to Google Play Internal Testing
    needs: approval-test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - client: mahuat
            package: com.docwise.mahuat

          - client: omcuat
            package: com.docwise.omcuat

          - client: skruat
            package: com.docwise.skruat

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Node Modules
        run: npm ci

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Check Fastlane Version
        run: |
         cd android
         fastlane --version
         fastlane action upload_to_play_store


      - name: Install Gems
        run: |
         cd android
         bundle install


      - name: Check Fastlane Version
        run: |
         cd android
         bundle exec fastlane --version
         bundle exec fastlane action upload_to_play_store
        
     
      - name: Create Client Environment
        run: |
         mkdir -p src/config
  
         if [ "${{ matrix.client }}" = "mahuat" ]; then
         BASE_URL="${{ secrets.MAHUAT_BASE_URL }}"
         CLIENT_NAME="Mahuat"
         elif [ "${{ matrix.client }}" = "omcuat" ]; then
         BASE_URL="${{ secrets.OMCUAT_BASE_URL }}"
         CLIENT_NAME="Omcuat"
         else
         BASE_URL="${{ secrets.SKRUAT_BASE_URL }}"
         CLIENT_NAME="Skruat"
         fi

         printf 'export const BASE_URL = "%s";\nexport const CLIENT_NAME = "%s";\n' \
         "$BASE_URL" "$CLIENT_NAME" > src/config/env.js

      - name: Restore Play Service Account
        run: |
          mkdir -p android/fastlane
          echo '${{ secrets.PLAY_ACCOUNT_JSON }}' > android/fastlane/play-account.json

      - name: Restore Keystore Properties
        run: |
           echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > android/keystore.properties

           echo "=== Checking file ==="
           ls -la android
           test -f android/keystore.properties && echo "FOUND" || echo "NOT FOUND"


      - name: Verify keystore.properties
        run: |
          echo "===== android directory ====="
          ls -la android

          
          

      - name: Restore Release Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/docwise-release.keystore

      - name: Verify release keystore
        run: |
          echo "===== android/app ====="
          ls -la android/app
          
      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Capitalize Flavor Name
        run: |
          CLIENT=$(echo "${{ matrix.client }}" | sed 's/.*/\u&/')
          echo "CLIENT=$CLIENT" >> $GITHUB_ENV

      - name: Build Release AAB
        run: |
         cd android
         ./gradlew bundle${CLIENT}Release \
         -PVERSION_CODE=$(( ${{ github.run_number }} + 2 )) \
         -PVERSION_NAME=1.0.$(( ${{ github.run_number }} + 2 ))

      - name: Show AAB Location
        run: |
         echo "===== AAB Files ====="
         find android/app/build/outputs/bundle -type f

      - name: Upload to Google Play Internal Testing
        run: |
         cd android
         bundle exec fastlane deploy \
         client:${{ matrix.client }} \
         package:${{ matrix.package }}
   